# These are supported funding model platforms

github: stacknide # https://github.com/sponsors/stacknide
# open_collective: fs-prober # https://opencollective.com/fs-prober
buy_me_a_coffee: ashuvssut # https://www.buymeacoffee.com/ashuvssut
